### ISSUE TITLE
Implement Form.submit() method

### ISSUE THREAD

**Issue by vladkampov** [vict-shevchenko/reactive-mobx-form#18]
I'd like to have `Form.submit()` method for form submitting by external components or different parts of the application.

**Comment by vict-shevchenko** [comment]
Hi @vladkampov  👋. Hope you still need this. Starting from v 0.10.2 you can use `withFormData('formName')(YourComponent)`

const YourComponent = ({submit}) => (<button onClick={submit}>Exteranal submit</button>)
